import fs from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";

// Serves article read-aloud audio from the filesystem at request time. Audio
// generated by the admin panel lands in public/assets/article-audio after the
// server has started, and Next's static public/ serving only knows files
// present at boot — so these must be read dynamically.
const audioDir = path.resolve(process.cwd(), "public", "assets", "article-audio");

const MIME_TYPES: Record<string, string> = {
  ".mp3": "audio/mpeg",
  ".wav": "audio/wav",
};

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ filename: string }> }
) {
  const { filename } = await params;
  const safeName = filename.replace(/[^a-zA-Z0-9._-]/g, "");
  const mimeType = MIME_TYPES[path.extname(safeName).toLowerCase()];

  if (!safeName || safeName.includes("..") || !mimeType) {
    return NextResponse.json({ error: "Unsupported asset" }, { status: 404 });
  }

  try {
    const buffer = await fs.readFile(path.join(audioDir, safeName));
    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        "Content-Type": mimeType,
        "Cache-Control": "public, max-age=300, stale-while-revalidate=3600",
      },
    });
  } catch {
    return NextResponse.json({ error: "Asset not found" }, { status: 404 });
  }
}
