import fs from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";

// Serves blog images from the filesystem at request time. Images generated by
// the admin panel land in public/assets/blog after the server has started, and
// Next's static public/ serving only knows files present at boot — so these
// must be read dynamically.
const blogAssetsDir = path.resolve(process.cwd(), "public", "assets", "blog");

const MIME_TYPES: Record<string, string> = {
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
};

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ filename: string }> }
) {
  const { filename } = await params;
  const safeName = filename.replace(/[^a-zA-Z0-9._-]/g, "");
  const mimeType = MIME_TYPES[path.extname(safeName).toLowerCase()];

  if (!safeName || safeName.includes("..") || !mimeType) {
    return NextResponse.json({ error: "Unsupported asset" }, { status: 404 });
  }

  try {
    const buffer = await fs.readFile(path.join(blogAssetsDir, safeName));
    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        "Content-Type": mimeType,
        "Cache-Control": "public, max-age=300, stale-while-revalidate=3600",
      },
    });
  } catch {
    return NextResponse.json({ error: "Asset not found" }, { status: 404 });
  }
}
